/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package script.analyze;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.List;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
//    	String[] a = {"a", "b", "c"};
//        List<String> list = Arrays.asList(a);
//        list.add("d");
//        list.add("e");
//        System.out.println(list);
        
        
        long x = 12L;
        long y = 10L;
        long b = -Math.floorDiv(x, -y);
        System.out.println("b=" + b);
        long c = (long) Math.ceil( 1.0 * x / y);
        System.out.println("c=" + c);
        long d = new Double(Math.ceil(1.0 * x / y)).longValue();
        System.out.println("d=" + d);
    }
    
    
    static class Arrays{
    	public static <T> ArrayList<T> asList(T... a) {
			return new ArrayList<>(java.util.Arrays.asList(a));
		}
    }
}
